mrc-rowers-hub/mrc-condition-checker

condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/openweatherapi/WeatherData.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/model/openweatherapi/WeatherDataTests.java
- Added WeatherDataTests class
- Added test for WeatherData.kelvinToCelsius
- Added method to convert temp from K to C
=> Convert K to C

condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/openweatherapi/WeatherData.java, condition-checker/src/main/resources/application.yml, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/WireMockSpecificDtBaseTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/WiremockBaseTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/mockSetup/MockOpenWeatherResponseGenerator.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/mockSetup/WireMockSetup.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/mockTests/WiremockSpecificDtSetupTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/utils/TestOpenWeatherUtils.java
- Setup wiremock for specific datetime 
- 
https://github.com/AdelaideBaron/condition-checker/pull/40 set as the base, as this is based off of that. https://github.com/AdelaideBaron/condition-checker/pull/40 should be merged first, and this will then be merging into master - this change of base is just to accurately reflect the size of this PR.
=> 35 new wiremock for dt calls

condition-checker/pom.xml, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/ConditionController.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/openweather/OpenWeatherApiClient.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/util/DateUtil.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/StatusCodeObject.java, condition-checker/src/main/resources/application.yml, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/WireMockSpecificDtBaseTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/openWeather/OpenWeatherApiClientTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/util/DateUtilTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/mockSetup/WireMockSetup.java
=> Call api implementation

condition-checker/pom.xml, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/boats/BoatCapabilityClient.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/mapper/SessionConditionsMapper.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/util/DateUtil.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/openweatherapi/OpenWeatherResponse.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/openweatherapi/WeatherData.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/response/SessionConditions.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/mapper/SessionConditionsMapperTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/util/DateUtilTests.java
=> Session conditions mapper

condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/mapper/SessionConditionsMapperTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/mockSetup/MockOpenWeatherResponseGenerator.java
=> updating wind speed handlers

condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/mapper/SessionConditionsMapper.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/openweather/OpenWeatherApiClient.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/response/SessionConditions.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/mapper/SessionConditionsMapperTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/openWeather/OpenWeatherApiClientTests.java
- Refactoring to add the status to session response messages
=> 32 add status to response

condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/ConditionController.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/boats/BoatCapabilityClient.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/config/ClockConfig.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/mapper/SessionConditionsMapper.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/openweather/OpenWeatherApiClient.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/util/DateUtil.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/response/ConditionResponse.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/WireMockSpecificDtBaseTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/mapper/SessionConditionsMapperTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/openWeather/OpenWeatherApiClientTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/util/DateUtilTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/mockSetup/MockOpenWeatherResponseGenerator.java
=> 33 give response

condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/boats/BoatCapabilityClient.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/boats/config/BoatConfig.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/boat/BoatLimits.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/openweatherapi/OpenWeatherResponse.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/openweatherapi/WeatherData.java, condition-checker/src/main/resources/application.yml, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/WireMockSpecificDtBaseTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/boats/BoatCapabilityClientTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/mapper/SessionConditionsMapperTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/model/openweatherapi/WeatherDataTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/mockSetup/MockOpenWeatherResponseGenerator.java
- Using units from open weather, imperial - as this provides for the hour, mph, which converts to kmh more accurately
=> 55 change to using unit on api calls to mph and convert that to kmh

README.md, condition-checker/Dockerfile, condition-checker/pom.xml, condition-checker/src/main/resources/application.yml
- Creating the image from dockerfile
=> Deployment 1

README.md, condition-checker/pom.xml, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/openweatherapi/WeatherData.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/WiremockBaseTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/mapper/SessionConditionsMapperTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/openWeather/OpenWeatherApiClientTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/util/DateUtilTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/mockTests/WireMockSetupTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/mockTests/WiremockSpecificDtSetupTests.java
- Addressed issues running app in EC2, such as tests (e.g. wiremock, or clock) and lack of mvn plugin in pom
=> Deployment

condition-checker/src/main/resources/templates/dateDetails.html, condition-checker/src/main/resources/templates/index.html
=> updating titles in html

condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/mapper/SessionConditionsMapper.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/response/ConditionResponseClient.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/util/DateUtil.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/openweatherapi/WeatherData.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/response/SessionConditions.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/response/TimeType.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/view/ThymeleafController.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/mapper/SessionConditionsMapperTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/util/DateUtilTests.java
Reverts AdelaideBaron/condition-checker#69
=> Revert "48 check conditions during session"

condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/mapper/SessionConditionsMapper.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/response/ConditionResponseClient.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/util/DateUtil.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/openweatherapi/WeatherData.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/response/SessionConditions.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/response/TimeType.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/view/ThymeleafController.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/mapper/SessionConditionsMapperTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/util/DateUtilTests.java
Reverts AdelaideBaron/condition-checker#73
=> Revert "Revert "48 check conditions during session""

condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/boats/BoatCapabilityClient.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/controller/response/ConditionResponseClient.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/view/ThymeleafController.java, condition-checker/src/main/resources/static/styles.css, condition-checker/src/main/resources/templates/dateDetails.html, condition-checker/src/main/resources/templates/index.html, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/WiremockBaseTests.java
- Display the session info on the website
=> 48 display session info on website

condition-checker/pom.xml
=> adding port

condition-checker/pom.xml
Reverts AdelaideBaron/mrc-condition-checker#82
=> Revert "adding port"

condition-checker/pom.xml
Reverts AdelaideBaron/mrc-condition-checker#83
=> Revert "Revert "adding port""

condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/openweatherapi/OpenWeatherResponse.java, condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/model/openweatherapi/WeatherData.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/controller/mapper/SessionConditionsMapperTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/applicationTests/model/openweatherapi/WeatherDataTests.java, condition-checker/src/test/java/com/mersey/rowing/club/condition_checker/mockSetup/MockOpenWeatherResponseGenerator.java
- remove kmh conversion, keep as mph
=> remove conversion to km/h

condition-checker/src/main/resources/templates/dateDetails.html
Changed km/h to mph on frontend in weather checker
=> MRC-81 Changing km/h to mph

condition-checker/src/main/java/com/mersey/rowing/club/condition_checker/view/ThymeleafController.java
- Added sorting logic to the session conditions map
- Need to keep an eye on this to make sure it doesn't happen again as the issue seemed to occur at random times
=> Fixing Sorting of Sessions

README.md, condition-checker/Dockerfile
=> readme update
